/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class newJFrame extends javax.swing.JFrame {

    /** Creates new form newJFrame */
    public newJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grandePainel = new javax.swing.JPanel();
        painelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        areaVivosMortos = new javax.swing.JPanel();
        caraVivo = new javax.swing.JPanel();
        numeroVivo = new javax.swing.JLabel();
        labelNumPessoas = new javax.swing.JLabel();
        labelIntervaloMorte = new javax.swing.JLabel();
        labelTempoEspera = new javax.swing.JLabel();
        botaoIniciar = new javax.swing.JButton();
        botaoRecomecar = new javax.swing.JButton();
        inputNumPessoas = new javax.swing.JTextField();
        inputIntervaloMorte = new javax.swing.JTextField();
        inputTempoEspera = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grandePainel.setBackground(new java.awt.Color(223, 230, 233));

        painelTitulo.setBackground(new java.awt.Color(87, 101, 116));

        labelTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(223, 230, 233));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("JOSEPHUS");

        org.jdesktop.layout.GroupLayout painelTituloLayout = new org.jdesktop.layout.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelTituloLayout.createSequentialGroup()
                .add(140, 140, 140)
                .add(labelTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(140, 140, 140))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelTituloLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(labelTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(22, 22, 22))
        );

        areaVivosMortos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        areaVivosMortos.setMaximumSize(new java.awt.Dimension(30, 30));
        areaVivosMortos.setMinimumSize(new java.awt.Dimension(30, 30));
        areaVivosMortos.setPreferredSize(new java.awt.Dimension(30, 30));
        areaVivosMortos.setLayout(new java.awt.GridLayout(4, 0, 5, 5));

        caraVivo.setBackground(new java.awt.Color(51, 255, 51));
        caraVivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caraVivo.setLayout(new java.awt.GridBagLayout());

        numeroVivo.setText("1");
        caraVivo.add(numeroVivo, new java.awt.GridBagConstraints());

        areaVivosMortos.add(caraVivo);

        labelNumPessoas.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelNumPessoas.setText("Numero de Pessoas");

        labelIntervaloMorte.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelIntervaloMorte.setText("Intervalo de morte");

        labelTempoEspera.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTempoEspera.setText("Tempo de espera");

        botaoIniciar.setText("Iniciar");

        botaoRecomecar.setText("Recomecar");

        org.jdesktop.layout.GroupLayout grandePainelLayout = new org.jdesktop.layout.GroupLayout(grandePainel);
        grandePainel.setLayout(grandePainelLayout);
        grandePainelLayout.setHorizontalGroup(
            grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, painelTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(grandePainelLayout.createSequentialGroup()
                .add(33, 33, 33)
                .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(grandePainelLayout.createSequentialGroup()
                        .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelNumPessoas)
                            .add(inputNumPessoas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(114, 114, 114)
                        .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelIntervaloMorte)
                            .add(inputIntervaloMorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(114, 114, 114)
                        .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelTempoEspera)
                            .add(inputTempoEspera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(grandePainelLayout.createSequentialGroup()
                        .add(botaoIniciar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(botaoRecomecar))
                    .add(areaVivosMortos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        grandePainelLayout.setVerticalGroup(
            grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(grandePainelLayout.createSequentialGroup()
                .add(painelTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(labelIntervaloMorte)
                        .add(labelTempoEspera))
                    .add(labelNumPessoas))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(inputNumPessoas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(inputIntervaloMorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(inputTempoEspera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(areaVivosMortos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(grandePainelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botaoIniciar)
                    .add(botaoRecomecar))
                .add(30, 30, 30))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(grandePainel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(grandePainel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaVivosMortos;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoRecomecar;
    private javax.swing.JPanel caraVivo;
    private javax.swing.JPanel grandePainel;
    private javax.swing.JTextField inputIntervaloMorte;
    private javax.swing.JTextField inputNumPessoas;
    private javax.swing.JTextField inputTempoEspera;
    private javax.swing.JLabel labelIntervaloMorte;
    private javax.swing.JLabel labelNumPessoas;
    private javax.swing.JLabel labelTempoEspera;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel numeroVivo;
    private javax.swing.JPanel painelTitulo;
    // End of variables declaration//GEN-END:variables

}
